name: Update Google Scholar Stats

on:
  schedule:
    - cron: '0 8 */3 * *'  # 每三天在中国时间 16:00 (UTC+8) 运行
  workflow_dispatch: 
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Create data directory
        run: |
          mkdir -p data
          
      # - name: Test citation stats script
      #   run: |
      #     TEST_MODE=1 python .github/scripts/update_citations.py
      #   env:
      #     GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
          
      - name: Update citation stats (main script)
        id: main_script
        run: python .github/scripts/update_citations.py
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        continue-on-error: true  # 即使失败也继续执行
        
      - name: Run fallback script if main script failed
        if: steps.main_script.outcome == 'failure'
        run: |
          echo "Main script failed, running fallback script..."
          python .github/scripts/fallback_update.py
          
      - name: Check if data file exists
        run: |
          if [ ! -f data/scholar_data.json ]; then
            echo "Data file not found, running fallback script..."
            python .github/scripts/fallback_update.py
          fi
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Google Scholar stats" && git push)
